# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, beta ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: main
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo `awk -F= '/version=/{print $2}' platform.txt`
          VERSION=`awk -F= '/version=/{print $2}' platform.txt`
          echo $VERSION
          echo "Version is $VERSION"
          echo "VERSION=$VERSION" >>$GITHUB_ENV
          echo '::set-output name=VERSION::$VERSION'
          tar --transform "s,^,imxrt/,S" -cvjf qNimble_iMXRT-$VERSION.tar.bz2 *
          echo $GITHUB_REF
          echo ${{env.VERSION}}
          echo ${{github.ref}}
          echo ${{github.ref != 'ref/heads/main'}}
          if [[ ${{github.ref}} == 'ref/heads/main' ]] ; then 
             echo "prerelease=false" >> $GITHUB_ENV
          else
             echo "prerelease=true" >> $GITHUB_ENV
          fi

      # make tarball release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{env.VERSION}}
            release_name: ${{env.VERSION}}
            body: Release ${{env.VERSION}} of qNimble Board Libraries for Arduino
            prerelease: ${{env.prerelease}}
      
      - name : Upload file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: qNimble_iMXRT-${{env.VERSION}}.tar.bz2      
          tag: ${{ env.VERSION }}
          overwrite: true
          body: "Release ${{env.VERSION}} of qNimble Board Libraries for Arduino"
